In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [17]:
matches = pd.read_csv("Dataset/matches.csv")
deliveries = pd.read_csv("Dataset/deliveries.csv")

print("Matches Shape :", matches.shape)
print("Deliveries Shape :", deliveries.shape)

Matches Shape : (1095, 20)
Deliveries Shape : (260920, 17)

In [18]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [19]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [20]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [21]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [22]:
print(matches.columns)

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [23]:
print(deliveries.columns)

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [24]:
print(deliveries["batting_team"].unique())

['Kolkata Knight Riders' 'Royal Challengers Bangalore'
 'Chennai Super Kings' 'Kings XI Punjab' 'Rajasthan Royals'
 'Delhi Daredevils' 'Mumbai Indians' 'Deccan Chargers'
 'Kochi Tuskers Kerala' 'Pune Warriors' 'Sunrisers Hyderabad'
 'Rising Pune Supergiants' 'Gujarat Lions' 'Rising Pune Supergiant'
 'Delhi Capitals' 'Punjab Kings' 'Lucknow Super Giants' 'Gujarat Titans'
 'Royal Challengers Bengaluru']

In [25]:
print(deliveries["bowling_team"].unique())

['Royal Challengers Bangalore' 'Kolkata Knight Riders' 'Kings XI Punjab'
 'Chennai Super Kings' 'Delhi Daredevils' 'Rajasthan Royals'
 'Mumbai Indians' 'Deccan Chargers' 'Kochi Tuskers Kerala' 'Pune Warriors'
 'Sunrisers Hyderabad' 'Rising Pune Supergiants' 'Gujarat Lions'
 'Rising Pune Supergiant' 'Delhi Capitals' 'Punjab Kings' 'Gujarat Titans'
 'Lucknow Super Giants' 'Royal Challengers Bengaluru']

In [26]:
teams = [
    'Chennai Super Kings',
    'Delhi Capitals',
    'Mumbai Indians',
    'Kolkata Knight Riders',
    'Punjab Kings',
    'Rajasthan Royals',
    'Royal Challengers Bangalore',
    'Sunrisers Hyderabad',
    'Lucknow Super Giants',
    'Gujarat Titans'
]

deliveries = deliveries[
    deliveries['batting_team'].isin(teams) &
    deliveries['bowling_team'].isin(teams)
]

deliveries.shape

(147829, 17)

In [27]:
deliveries['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Mumbai Indians', 'Chennai Super Kings', 'Rajasthan Royals',
       'Sunrisers Hyderabad', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans'], dtype=object)

In [28]:
total_score_df = deliveries.groupby(['match_id','inning']).sum()['total_runs'].reset_index()
total_score_df.head()

   match_id  inning  total_runs
0    335982       1         222
1    335982       2          82
2    335985       1         165
3    335985       2         166
4    335989       1         208

In [29]:
total_score_df = total_score_df[total_score_df['inning'] == 1]
total_score_df.head()

   match_id  inning  total_runs
0    335982       1         222
2    335985       1         165
4    335989       1         208
6    335992       1         135
8    335993       1         147

In [30]:
match_df = matches.merge(total_score_df, left_on='id', right_on='match_id')
match_df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,match_id,inning,total_runs
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,335982,1,222
1,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,335985,1,165
2,335989,2007/08,Chennai,2008-04-23,League,ML Hayden,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,...,6.0,209.0,20.0,N,NaN,DJ Harper,GA Pratapkumar,335989,1,208
3,335992,2007/08,Bangalore,2008-04-26,League,SR Watson,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,...,7.0,136.0,20.0,N,NaN,MR Benson,IL Howell,335992,1,135
4,335993,2007/08,Chennai,2008-04-26,League,JDP Oram,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,...,9.0,148.0,20.0,N,NaN,BF Bowden,AV Jayaprakash,335993,1,147

In [31]:
match_df = match_df[['match_id',
                     'city',
                     'winner',
                     'total_runs']]

In [32]:
match_df.head()

   match_id       city                       winner  total_runs
0    335982  Bangalore        Kolkata Knight Riders         222
1    335985     Mumbai  Royal Challengers Bangalore         165
2    335989    Chennai          Chennai Super Kings         208
3    335992  Bangalore             Rajasthan Royals         135
4    335993    Chennai          Chennai Super Kings         147

In [33]:
match_df = match_df.merge(deliveries, on='match_id')
match_df.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,Bangalore,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,Bangalore,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,Bangalore,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,Bangalore,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,Bangalore,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [34]:
match_df = match_df[match_df['inning'] == 1]
match_df.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,Bangalore,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,Bangalore,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,Bangalore,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,Bangalore,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,Bangalore,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [35]:
match_df.shape

(76380, 20)

In [36]:
match_df['current_score'] = match_df.groupby('match_id')['total_runs_y'].cumsum()

In [37]:
match_df[['match_id','over','ball','total_runs_y','current_score']].head(10)

   match_id  over  ball  total_runs_y  current_score
0    335982     0     1             1              1
1    335982     0     2             0              1
2    335982     0     3             1              2
3    335982     0     4             0              2
4    335982     0     5             0              2
5    335982     0     6             0              2
6    335982     0     7             1              3
7    335982     1     1             0              3
8    335982     1     2             4              7
9    335982     1     3             4             11

In [38]:
match_df['player_dismissed'] = match_df['player_dismissed'].fillna("0")
match_df['wickets'] = match_df['player_dismissed'].apply(lambda x: 0 if x=="0" else 1)
match_df['wickets'] = match_df.groupby('match_id')['wickets'].cumsum()

In [39]:
match_df[['match_id','over','ball','player_dismissed','wickets']].head(20)

    match_id  over  ball player_dismissed  wickets
0     335982     0     1                0        0
1     335982     0     2                0        0
2     335982     0     3                0        0
3     335982     0     4                0        0
4     335982     0     5                0        0
5     335982     0     6                0        0
6     335982     0     7                0        0
7     335982     1     1                0        0
8     335982     1     2                0        0
9     335982     1     3                0        0
10    335982     1     4                0        0
11    335982     1     5                0        0
12    335982     1     6                0        0
13    335982     2     1                0        0
14    335982     2     2                0        0
15    335982     2     3                0        0
16    335982     2     4                0        0
17    335982     2     5                0        0
18    335982     2     6                0        0
19    335982     3     1                0        0

In [40]:
match_df['overs'] = match_df['over'] + (match_df['ball'] / 10)

In [41]:
match_df[['over','ball','overs']].head(15)

    over  ball  overs
0      0     1    0.1
1      0     2    0.2
2      0     3    0.3
3      0     4    0.4
4      0     5    0.5
5      0     6    0.6
6      0     7    0.7
7      1     1    1.1
8      1     2    1.2
9      1     3    1.3
10     1     4    1.4
11     1     5    1.5
12     1     6    1.6
13     2     1    2.1
14     2     2    2.2

In [42]:
match_df['overs'] = match_df['over'] + (match_df['ball']/10)

In [44]:
match_df.shape

(76380, 23)

In [45]:
match_df['balls_bowled'] = (match_df['over'] * 6) + match_df['ball']

In [46]:
match_df[['over','ball','balls_bowled']].head(15)

    over  ball  balls_bowled
0      0     1             1
1      0     2             2
2      0     3             3
3      0     4             4
4      0     5             5
5      0     6             6
6      0     7             7
7      1     1             7
8      1     2             8
9      1     3             9
10     1     4            10
11     1     5            11
12     1     6            12
13     2     1            13
14     2     2            14

In [47]:
match_df = match_df[match_df['balls_bowled'] >= 30]
match_df.shape

(57836, 24)

In [50]:
match_df = match_df.copy()
match_df['balls_left'] = 120 - match_df['balls_bowled']

In [51]:
match_df['wickets_left'] = 10 - match_df['wickets']

In [52]:
match_df[['balls_bowled','balls_left','wickets','wickets_left']].head(10)

    balls_bowled  balls_left  wickets  wickets_left
31            30          90        0            10
32            31          89        0            10
33            32          88        1             9
34            33          87        1             9
35            34          86        1             9
36            35          85        1             9
37            36          84        1             9
38            37          83        1             9
39            38          82        1             9
40            39          81        1             9

In [53]:
match_df['crr'] = (match_df['current_score'] * 6) / match_df['balls_bowled']

In [54]:
match_df[['current_score','balls_bowled','crr']].head(10)

    current_score  balls_bowled        crr
31             60            30  12.000000
32             61            31  11.806452
33             61            32  11.437500
34             61            33  11.090909
35             61            34  10.764706
36             61            35  10.457143
37             61            36  10.166667
38             62            37  10.054054
39             63            38   9.947368
40             64            39   9.846154

In [55]:
match_df = match_df[match_df['balls_left'] != 0]
match_df.shape

(57255, 27)

In [56]:
final_df = match_df[['batting_team',
                     'bowling_team',
                     'city',
                     'current_score',
                     'balls_left',
                     'wickets_left',
                     'crr',
                     'total_runs_x']]

In [57]:
final_df.head()

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,total_runs_x
31,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,60,90,10,12.000000,222
32,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,61,89,10,11.806452,222
33,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,61,88,9,11.437500,222
34,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,61,87,9,11.090909,222
35,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,61,86,9,10.764706,222

In [58]:
final_df.shape

(57255, 8)

In [59]:
final_df.isnull().sum()

batting_team        0
bowling_team        0
city             3180
current_score       0
balls_left          0
wickets_left        0
crr                 0
total_runs_x        0
dtype: int64

In [60]:
final_df = final_df.dropna()

In [61]:
final_df.shape

(54075, 8)

In [62]:
final_df = final_df.sample(final_df.shape[0])

In [63]:
final_df.head()

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,total_runs_x
8908,Rajasthan Royals,Kolkata Knight Riders,Durban,59,65,6,6.436364,101
79560,Kolkata Knight Riders,Sunrisers Hyderabad,Abu Dhabi,147,6,6,7.736842,163
68248,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata,117,32,8,7.977273,213
18298,Royal Challengers Bangalore,Chennai Super Kings,Mumbai,66,65,8,7.200000,175
61955,Sunrisers Hyderabad,Chennai Super Kings,Mumbai,71,64,8,7.607143,178

In [64]:
X = final_df.drop(columns='total_runs_x')
y = final_df['total_runs_x']

In [65]:
print(X.shape)
print(y.shape)

(54075, 7)
(54075,)

In [66]:
from sklearn.model_selection import train_test_split

In [67]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [71]:
print(X_train.shape)
print(X_test.shape)

(43260, 7)
(10815, 7)

In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [74]:
trf = ColumnTransformer(
    transformers=[
        (
            'trf',
            OneHotEncoder(handle_unknown='ignore'),
            ['batting_team', 'bowling_team', 'city']
        )
    ],
    remainder='passthrough'
)

In [75]:
X_train = trf.fit_transform(X_train)
X_test = trf.transform(X_test)

In [76]:
print("X_train Shape :", X_train.shape)
print("X_test Shape :", X_test.shape)

X_train Shape : (43260, 53)
X_test Shape : (10815, 53)

In [81]:
from tensorflow.keras import Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Input(shape=(53,)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

In [82]:
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [83]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=32
)

Epoch 1/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 688.9769 - mae: 16.2877 - val_loss: 332.7485 - val_mae: 13.2122
Epoch 2/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 321.8360 - mae: 13.2256 - val_loss: 315.4614 - val_mae: 12.9759
Epoch 3/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 315.2861 - mae: 13.1925 - val_loss: 344.5059 - val_mae: 14.0947
Epoch 4/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - loss: 310.6606 - mae: 13.0757 - val_loss: 310.0920 - val_mae: 12.9519
Epoch 5/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 302.7324 - mae: 12.9069 - val_loss: 314.8902 - val_mae: 13.1299
Epoch 6/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 298.7008 - mae: 12.8185 - val_loss: 302.5222 - val_mae: 12.7542
Epoch 7/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 292.5662 - mae: 12.6777 - val_loss: 311.4376 - val_mae: 13.3563
Epoch 8/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 283.5154 - mae: 12.4740 - val_loss: 279.5347 - val_mae: 12.3222
Epoch 9/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 276.2193 - mae: 12.3268 - val_loss: 290.5901 - val_mae: 12.5573
Epoch 10/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 265.7467 - mae: 12.0590 - val_loss: 270.4459 - val_mae: 12.1855
Epoch 11/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 256.6481 - mae: 11.8463 - val_loss: 253.0892 - val_mae: 11.6011
Epoch 12/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 245.7748 - mae: 11.5578 - val_loss: 251.6782 - val_mae: 11.5754
Epoch 13/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 234.3712 - mae: 11.2673 - val_loss: 226.7260 - val_mae: 11.0137
Epoch 14/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 225.7223 - mae: 11.0538 - val_loss: 226.1386 - val_mae: 11.0129
Epoch 15/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 219.8112 - mae: 10.9058 - val_loss: 221.1156 - val_mae: 10.9332
Epoch 16/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 212.7138 - mae: 10.7048 - val_loss: 213.6464 - val_mae: 10.8151
Epoch 17/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 206.7022 - mae: 10.5486 - val_loss: 244.7778 - val_mae: 11.3462
Epoch 18/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 200.8038 - mae: 10.3541 - val_loss: 197.5449 - val_mae: 10.1858
Epoch 19/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 195.4602 - mae: 10.2270 - val_loss: 201.0753 - val_mae: 10.2862
Epoch 20/20
1352/1352 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 192.1222 - mae: 10.1458 - val_loss: 230.8204 - val_mae: 11.0536

In [84]:
loss, mae = model.evaluate(X_test, y_test)

print("Loss:", loss)
print("MAE:", mae)

338/338 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 230.8204 - mae: 11.0536
Loss: 230.8204345703125
MAE: 11.053610801696777

In [85]:
predictions = model.predict(X_test)
predictions[:10]

338/338 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step

array([[177.19533],
       [190.41493],
       [185.07729],
       [150.0559 ],
       [174.21722],
       [163.36128],
       [229.89342],
       [210.61345],
       [182.2617 ],
       [142.95485]], dtype=float32)

In [86]:
model.save("Model/ipl_score_prediction_model.keras")

In [87]:
print("Model Saved Successfully!")

Model Saved Successfully!

In [88]:
import pickle

pickle.dump(trf, open("Model/transformer.pkl", "wb"))

In [89]:
print("Transformer Saved Successfully!")

Transformer Saved Successfully!